### PR TITLE
Add timeout to ms_dotnet4

### PR DESCRIPTION
**Pull request by rcolanero**
Added timeout for .NET 4 install, same as for .NET 4.5 cookbook ms_dotnet45

### CODE REVIEW

**Comment by rcolanero** [comment]
Any updates on pull request review?

**Comment by rcolanero** [comment]
@kendrickm Any updates on status or review?

**Comment by tas50** [comment]
@rcolanero If you want to rebase this without the version bump I'd be happy to merge it.

**Comment by tas50** [comment]
Closing this out since we've deprecated this cookbook in favor of the ms_dotnet cookbook

**Pull request closed without merging**
